version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: eclat_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-eclat_db}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build:
      context: ../server
      dockerfile: Dockerfile
    container_name: eclat_api
    restart: unless-stopped
    env_file:
      - ../server/.env
    depends_on:
      - db
    ports:
      - "4000:4000"

  frontend:
    build:
      context: ..
      dockerfile: deploy/frontend.Dockerfile
    container_name: eclat_frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "80:80"

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"

volumes:
  db_data:
